version: '3.8'

services:
  invokeai:
    image: ghcr.io/invoke-ai/invokeai
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN}
    ports:
      - "9090:9090"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - invokeai_data:/home/myuser/invokeai

volumes:
  invokeai_data:
