services:
  invokeai:
    image: ghcr.io/invoke-ai/invokeai
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HUGGING_FACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_HUB_TOKEN}
    ports:
      - "9090:9090"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - invokeai_data:/home/myuser/invokeai
      - ./models:/models

volumes:
  invokeai_data:
